version: '3.9'

services:
  mysql:
    image: mysql:8
    ports:
      - "3306:3306"
    volumes:
      - mysql_volume:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_PASSWORD=1234
      - MYSQL_USER=bankan
      - MYSQL_DATABASE=bankan

volumes:
  mysql_volume: